### ISSUE TITLE
Argument "read_min" in clean_reads.py

### ISSUE THREAD

**Issue by Estel-Kitsune** [AntonelliLab/palm_pipeline#1]
Hi,

The wiki page for **trimming and filtering** needs to be modified.

On the wiki, the argument is **--read-min**, but in your script, it's **--read_min**. If you use --read-min, you get the following error:
clean_reads.py: error: unrecognized arguments: --read-min 150000

**Comment by tobiashofmann88** [comment]
Thanks,
I fixed it now.
